services:
  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=companyres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 3s